#!/bin/sh
if [[ $1 == '' ]]; then
    echo 'This script must be run in one of the following manners:'
    echo 'start  - start the video server daemon'
else
	if [ "$1" = "start"  ]; then
		/usr/local/bin/camera_server -d
	fi
fi
exit 0;